services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      dev-migrate:
        condition: service_completed_successfully
    networks:
      - tevira_net

  dev-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration_service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: alembic upgrade head
    env_file:
      - .env.dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tevira_net

  postgres:
    image: postgres:18
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_dev_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - tevira_net

volumes:
  postgres_dev_data:

networks:
  tevira_net:
    driver: bridge