"""initial_schema

Revision ID: f1a10b754cd1
Revises: 
Create Date: 2026-08-12 15:38:47.936487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1a10b754cd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('current_state', sa.String(), nullable=True),
    sa.Column('last_session', sa.String(), nullable=True),
    sa.Column('open_loops', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('next_actions', sa.String(), nullable=True),
    sa.Column('important_context', sa.String(), nullable=True),
    sa.Column('blockers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', native_enum=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'done', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('progress_notes')
    op.drop_table('projects')
    # ### end Alembic commands ###
