name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Copy the Dummy Environment Files
        run: mv .env.example .env &&

      - name: Run the Test Suite
        run: docker compose -f docker-compose.test.yml up --build --exit-code-from test

      - name: Cleanup Docker Test Image
        run: docker compose down -v --remove-orphans

      - name: Build the Production Docker Stack
        run: docker compose up --build --wait

      - name: Production Image Health Check
        run: curl -X 'GET' 'http://127.0.0.1:8000/health'

      - name: Cleanup Docker Production Image
        run: docker compose down -v --remove-orphans
